language: python

# Environment changes have to be manually synced with 'tox.ini'.
# See: https://github.com/travis-ci/travis-ci/issues/3024

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.5"
  - "pypy3.6"

install:
  - pip install poetry
  - poetry install -v

script:
  - poetry run py.test tests/

after_success:
  - poetry run coveralls
